---
title: "Untitled"
author: "Maria"
date: "3/4/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# packages
pacman::p_load(tidyverse, lmerTest)
```

Read experimental data

```{r, warning = FALSE}

# list all csv files in the directory
pavlovia <- list.files(
  path = "C:/Users/maria/Downloads/pls_3",
  pattern = "*.csv",
  full.names = TRUE
) %>%
  
  map_dfr(~ read_csv(.x,
    col_types = cols(

      # set class as numeric 
      
        # -- reaction time columns 
        edited_character_resp.rt = col_double(),
        original_character_resp.rt = col_double(),
        gaze_response.rt = col_double(),
        landscapeA_resp.rt = col_double(),
        landscapeB_resp.rt = col_double(),
        seed_response.rt = col_double(),
        token_edited_resp.rt = col_double(),
        token_original_resp.rt = col_double(),
        tree_response.rt = col_double(),
      
        # -- trial number columns
        trials_seeds.thisN = col_double(),
        trials_tree.thisN = col_double(),
        trials_sight_color.thisN = col_double(),
        trials_character_edited.thisN = col_double(),
        trials_character_original.thisN = col_double(),
        trials_gaze.thisN = col_double(),
        trials_seeds.thisN = col_double(),
        trials_sight_black.thisN = col_double(),
        trials_sight_color.thisN = col_double(),
        trials_tokens_edited.thisN = col_double(),
        trials_tokens_original.thisN = col_double(),
      
      # set all others as factors
      .default = col_factor()
    )
  ))



# if you have specific levels for factors, you can specify them within the col_factor() function
# col_factor(levels = NULL)

# check to see ratio between condition A and B
(length(unique(pavlovia$edited_character_resp.rt)) - 1) / 4
(length(unique(pavlovia$original_character_resp.rt)) - 1) / 4

```

Read survey data

```{r}
temp_survey <- read_csv2("C:/Users/maria/Downloads/dataset_15-03.csv") %>% 

  # make labels intuitive based on translations from labels.csv

  # gender
  mutate(gender = as.factor(
    ifelse(gender == 1, "Female",
    ifelse(gender == 2, "Male",
                        "Other"
      )
    )
  )) %>%
  
  # color deficiency
  mutate(colorblind = factor(
    ifelse(colorblind == 1, "Yes",
    ifelse(colorblind == 2, "No",
                            "Unsure"
      )
    ), 
    levels = c("No",
               "Yes",
               "Unsure")
  )) %>%
  
  # previous player experience
  mutate(played_tang = as.factor(
    ifelse(played_tang == 5, "Yes", "No")
    )) %>%
  
  mutate(played_photo = as.factor(
    ifelse(played_photo == 5, "Yes", "No")
    )) %>%
  
  mutate(played_haven = as.factor(
    ifelse(played_haven == 5, "Yes", "No")
    )) %>%
  
  # board gaming frequency
  mutate(freq_game = factor(
    ifelse(freq_game == 1, "Weekly",
      ifelse(freq_game == 2, "Monthly",
        ifelse(freq_game == 3, "Every 3rd month",
         ifelse(freq_game == 4, "Semi-annually",
                                  "Rarely"
          )
        )
      )
    ), 
    levels = c("Weekly",
                "Monthly",
                "Every 3rd month",
                "Semi-annually",
                "Rarely")
  )) %>%
  
  # difficulty understanding rules
  mutate(diff_understand = factor(
    ifelse(diff_understand == 1, "Strongly agree",
      ifelse(diff_understand == 2, "Agree",
        ifelse(diff_understand == 3, "Neither nor",
          ifelse(diff_understand == 4, "Disagree",
          "Strongly disagree"
          )
        )
      )
    ), 
    levels = c("Strongly disagree",
               "Disagree",
               "Neither nor",
               "Agree",
               "Strongly agree")
  )) %>%
  
  # difficulty remembering rules
  mutate(diff_remember = factor(
    ifelse(diff_remember == 1, "Strongly agree",
      ifelse(diff_remember == 2, "Agree",
        ifelse(diff_remember == 3, "Neither nor",
          ifelse(diff_remember == 4, "Disagree",
          "Strongly disagree"
          )
        )
      )
    ), 
    levels = c("Strongly disagree",
               "Disagree",
               "Neither nor",
               "Agree",
               "Strongly agree")
  )) 


```

Merge dataframes and fix classes

```{r}
# merge dataframes
df <- merge(pavlovia, 
            temp_survey) %>%
  
  # compute missing binary column for correct responses for original character task
  mutate(original_character_resp.corr = ifelse(
    as.character(original_character_resp.keys) == as.character(correct_character_options), 1,
    ifelse(is.na(original_character_resp.keys), NA, 0)
  )) %>%
  
  # make age be numeric
  mutate(age = as.numeric(age))

```

Make dataframes for each investigation, i.e. create better overview

```{r}
# task: seed tokens on the player board
df_seed <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correctSeednumber,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_photo,
    seed_options,
    seed_response.corr,
    seed_response.keys,
    seed_response.rt,
    trials_seeds.thisN
  ) %>% 
  
  # make dataframe appear compact by filtering out task-irrelevant rows
  filter(!is.na(seed_options)) %>%
  
  # create columns stating the experimental manipulation and stimulus variety
  mutate(board_color = as.factor(
    ifelse(str_extract(seed_options, "^.{3}") == "gul", "yellow", "orange")
  )) %>%
  
  mutate(manipulation = factor(
    ifelse(str_extract(seed_options, ".{4}(?=.{4}$)") == "grey", "edited", "original"), 
    levels = c("original",
               "edited") 
  )) %>% 
  
  # rename response time column
  rename(
    RT = seed_response.rt)

# ------------------------------------

# task: trees on the game board
df_trees <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correctTreenumber,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_photo,
    tree_options,
    tree_response.corr,
    tree_response.keys,
    tree_response.rt,
    trials_tree.thisN
  ) %>% 
  
  # make dataframe appear compact by filtering out task-irrelevant rows
  filter(!is.na(tree_options)) %>%
  
  # create columns stating the experimental manipulation and stimulus variety
  mutate(manipulation = factor(
    ifelse(str_extract(tree_options, "^.{4}") == "edit", "edited", "original"), 
    levels = c("original",
               "edited")
  )) %>%
  
  mutate(color_trees_to_count = as.factor(
    ifelse(str_extract(tree_options, "(?<=_).{4}") == "gree", "green",
      ifelse(str_extract(tree_options, "(?<=_).{4}") == "blue", "blue",
        ifelse(str_extract(tree_options, "(?<=_).{4}") == "oran", "orange",
          ifelse(str_extract(tree_options, "(?<=_).{4}") == "gulp", ifelse(manipulation == "edited", "pink", "yellow"),
            NA
          )
        )
      )
    )
  )) %>% 
  
  # rename response time column
  rename(
    RT = tree_response.rt)

# ------------------------------------

# task: token discernablity

df_tokens <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correct_token_options,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_haven,
    edited_token_options,
    original_token_options,
    token_original_resp.corr,
    token_edited_resp.corr,
    token_original_resp.keys,
    token_edited_resp.keys,
    token_original_resp.rt,
    token_edited_resp.rt,
    trials_tokens_edited.thisN,
    trials_tokens_original.thisN
  ) %>% 
  
  # make collective columns for stimuli, RT, etc. across condition
  mutate(token_options = as.factor(
    ifelse(is.na(original_token_options), as.character(edited_token_options), as.character(original_token_options))
    )) %>%
  
  mutate(RT = ifelse(is.na(token_edited_resp.rt), token_original_resp.rt, token_edited_resp.rt)) %>% 
  
  mutate(trials_tokens.thisN = as.numeric(
    ifelse(is.na(trials_tokens_edited.thisN), as.character(trials_tokens_original.thisN), as.character(trials_tokens_edited.thisN)
    ))) %>% 
  
  mutate(token_resp.corr = as.numeric(
    ifelse(is.na(token_edited_resp.corr), as.character(token_original_resp.corr), as.character(token_edited_resp.corr)
    ))) %>%  

  # remove old columns
  select(-original_token_options, 
         -edited_token_options, 
         -token_original_resp.rt, 
         -token_edited_resp.rt, 
         -token_edited_resp.corr, 
         -token_original_resp.corr, 
         -trials_tokens_edited.thisN, 
         -trials_tokens_original.thisN) %>% 
  
  # make dataframe appear compact by filtering out task and condition-irrelevant rows 
  filter(!is.na(RT)) %>%
  
    # create columns stating the experimental manipulation and stimulus variety
  mutate(manipulation = factor(
    ifelse(str_extract(token_options, "^.{4}") == "edit", "edited", "original"), 
    levels = c("original",
               "edited")
    )) %>%
  
  mutate(token_color = as.factor(
    ifelse(str_extract(token_options, "(?<=tokens_).{4}") == "blue", "blue", "green")
    )) 

# ------------------------------------

# task: gaze direction
df_gaze <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correctGazeanswer,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_tang,
    options,
    gaze_response.corr,
    gaze_response.keys,
    gaze_response.rt,
    trials_gaze.thisN,
  ) %>% 
  
  # make dataframe appear compact by filtering out task-irrelevant rows
  filter(!is.na(options)) %>%
  
  # create columns stating the experimental manipulation and stimulus variety
  mutate(manipulation = factor(
    ifelse(str_extract(options, "(?<=_).{3}") == "cue", "edited", "original"), 
    levels = c("original",
               "edited")
  )) %>%
  
  mutate(stimulus_type = as.factor(str_extract(options, ".{5}"))) %>% 
  
  # rename response time column
  rename(
    RT = gaze_response.rt)

# ------------------------------------

# task: character color match

df_character <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correct_character_options,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_tang,
    edited_character_options,
    original_character_options,
    edited_character_resp.corr,
    original_character_resp.corr,
    edited_character_resp.keys,
    original_character_resp.keys,
    edited_character_resp.rt,
    original_character_resp.rt,
    trials_character_edited.thisN,
    trials_character_original.thisN
  ) %>% 
  
  # make collective columns for stimuli, RT, etc. across condition
  mutate(character_options = as.factor(
    ifelse(is.na(original_character_options), as.character(edited_character_options), as.character(original_character_options))
    )) %>%
  
  mutate(RT = ifelse(is.na(edited_character_resp.rt), original_character_resp.rt, edited_character_resp.rt)) %>% 
  
  mutate(trials_character.thisN = as.numeric(
    ifelse(is.na(trials_character_edited.thisN), as.character(trials_character_original.thisN), as.character(trials_character_edited.thisN)
    ))) %>% 
  
  mutate(character_resp.corr = as.numeric(
    ifelse(is.na(edited_character_resp.corr), as.character(original_character_resp.corr), as.character(edited_character_resp.corr)
    ))) %>%  

  # remove old columns
  select(-original_character_options, 
         -edited_character_options, 
         -original_character_resp.rt, 
         -edited_character_resp.rt, 
         -original_character_resp.corr, 
         -edited_character_resp.corr, 
         -trials_character_original.thisN, 
         -trials_character_edited.thisN) %>% 
  
  # make dataframe appear compact by filtering out task and condition-irrelevant rows 
  filter(!is.na(RT)) %>%
  
    # create columns stating the experimental manipulation and stimulus variety
  mutate(manipulation = factor(
    ifelse(str_extract(character_options, "^.{4}") == "edit", "edited", "original"), 
    levels = c("original",
               "edited")
    )) %>%
  
  mutate(character_type = as.factor(
    ifelse(str_extract(character_options, "(?<=_).{4}") == "poet", "poet", 
      ifelse(str_extract(character_options, "(?<=_).{4}") == "herm", "hermit", 
        ifelse(str_extract(character_options, "(?<=_).{4}") == "monk", "monk", "architect")))
    ))

# ------------------------------------

# task: icon matching for sight symbols/landscapes

df_icon <- df %>%
  
  # select relevant columns
  select(
    id,
    age,
    colorblind,
    correct_landscape_options,
    diff_remember,
    diff_understand,
    freq_game,
    gender,
    played_tang,
    landscape_options,
    landscapeA_resp.corr,
    landscapeB_resp.corr,
    landscapeA_resp.keys,
    landscapeB_resp.keys,
    landscapeA_resp.rt,
    landscapeB_resp.rt,
    trials_sight_black.thisN,
    trials_sight_color.thisN
  ) %>% 
  
  # make collective columns for stimuli, RT, etc. across condition
  mutate(RT = ifelse(is.na(landscapeA_resp.rt), landscapeB_resp.rt, landscapeA_resp.rt)) %>% 
  
  mutate(trials.thisN = as.numeric(
    ifelse(is.na(trials_sight_black.thisN), as.character(trials_sight_color.thisN), as.character(trials_sight_black.thisN)
    ))) %>% 
  
  mutate(icon_resp.corr = as.numeric(
    ifelse(is.na(landscapeA_resp.corr), as.character(landscapeB_resp.corr), as.character(landscapeA_resp.corr)
    ))) %>%  

  # remove old columns
  select(
         -landscapeA_resp.rt, 
         -landscapeB_resp.rt, 
         -landscapeA_resp.corr, 
         -landscapeB_resp.corr, 
         -trials_sight_black.thisN, 
         -trials_sight_color.thisN) %>% 
  
  # make dataframe appear compact by filtering out task and condition-irrelevant rows 
  filter(!is.na(RT)) %>%
  
    # create columns stating the experimental manipulation and stimulus variety
  mutate(manipulation = factor(
    ifelse(str_extract(landscape_options, "(?<=_).{5}") == "color", "edited", "original"), 
    levels = c("original",
               "edited")
    )) 

```

Write cleaned data to csv files

```{r}
# list of dataframes and their corresponding file names
df_list <- list(df_seed,
                df_trees, 
                df_tokens, 
                df_gaze, 
                df_character, 
                df_icon)

file_names <- c("cleaned_data_task_seed.csv", 
                "cleaned_data_task_trees.csv", 
                "cleaned_data_task_tokens.csv", 
                "cleaned_data_task_gaze.csv", 
                "cleaned_data_task_character.csv", 
                "cleaned_data_task_icon.csv")

# path for cleaned data 
folder_path <- "../data/cleaned data"

# create the folder if it doesn't exist
if (!file.exists(folder_path)) {
  dir.create(folder_path)
}

# write data frames to csv files in the specified folder
for (i in seq_along(df_list)) {
  write.csv(df_list[[i]], file.path(folder_path, file_names[i]), row.names = FALSE)
}

```


Clean environment

```{r}
# remove
rm(df,
   df_list,
   file_names,
   folder_path,
   i,
   pavlovia, 
   temp_survey)

```

