---
title: "Untitled"
author: "Maria"
date: "3/19/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
pacman::p_load(tidyverse, patchwork, lmerTest)
```

Run the data cleaning .Rmd script

```{r, warning = FALSE}

file_name <- "Data cleaning.Rmd"
rmarkdown::render(file_name, quiet = TRUE)

rm(file_name)
```

Handle outliers before modelling

```{r}
# function for finding cutoff for outliers
upper_bound <- function(df, rt_term) {
  cutoff <- mean(df[[rt_term]]) + 3 * sd(df[[rt_term]])
  return(cutoff)
}

# list of dataframes 
df_list <- list(df_seed, 
                df_trees, 
                df_tokens, 
                df_gaze,
                df_character,
                df_icon)

# corresponding vector of dataframe names
df_names <- c("df_seed",
              "df_trees", 
              "df_tokens", 
              "df_gaze",
              "df_character",
              "df_icon")

# calculate and store upper bound for each dataframe
upper_bounds <- lapply(df_list, function(df) {
  upper_bound(df, "RT")
})

# function for replacing values exceeding the upper bounds
replace_outliers <- function(df_list, upper_bounds) {
  modified_dfs <- lapply(seq_along(df_list), function(i) {
    df <- df_list[[i]]
    
    # adjust RT values
    df <- df %>%
      mutate(RT = ifelse(
        RT >= upper_bounds[[i]], upper_bounds[[i]], RT)) %>% # replace values exceeding the upper boundary
      
      filter(RT > 0.1) # exclude unrealistically fast response times
    
    return(df)
  })
  
  return(modified_dfs)  # return the list of modified dataframes
}

# call function
modified_dfs_list <- replace_outliers(df_list, upper_bounds)

# loop through the list of modified dfs and assign each dataframe to its original name
for (i in seq_along(modified_dfs_list)) {
  assign(df_names[i], modified_dfs_list[[i]], envir = .GlobalEnv)
}

rm(modified_dfs_list,
   upper_bounds,
   df_names,
   i)

```

Plotting density distributions for response times

```{r}
# density plots of the distributions of outcome variables
seed_density <- ggplot(df_seed, aes(x = RT)) +
  geom_density(fill = "skyblue", color = "blue", alpha = 0.7) +
  labs(title = "Seed - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

tree_density <- ggplot(df_trees, aes(x = RT)) +
  geom_density(fill = "palegreen2", color = "palegreen4", alpha = 0.7) +
  labs(title = "Trees - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

token_density <- ggplot(df_tokens, aes(x = RT)) +
  geom_density(fill = "darkgoldenrod1", color = "darkgoldenrod", alpha = 0.7) +
  labs(title = "Token - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

gaze_density <- ggplot(df_gaze, aes(x = RT)) +
  geom_density(fill = "lightpink", color = "lightpink4", alpha = 0.7) +
  labs(title = "Gaze - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

character_density <- ggplot(df_character, aes(x = RT)) +
  geom_density(fill = "aquamarine", color = "aquamarine4", alpha = 0.7) +
  labs(title = "Character - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

icon_density <- ggplot(df_icon, aes(x = RT)) +
  geom_density(fill = "plum", color = "plum4", alpha = 0.7) +
  labs(title = "Icon - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

# plot using patchwork
denity_response_times <- 
  (seed_density+tree_density)/
  (token_density+gaze_density)/
  (character_density+icon_density)

denity_response_times

rm(seed_density,
   tree_density,
   token_density,
   gaze_density,
   character_density,
   icon_density)
```

Plotting density distributions for logged response times

```{r}
# density plots of the distributions of outcome variables -- logged response times
seed_density <- ggplot(df_seed, aes(x = log(RT))) +
  geom_density(fill = "skyblue", color = "blue", alpha = 0.7) +
  labs(title = "Seed - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

tree_density <- ggplot(df_trees, aes(x = log(RT))) +
  geom_density(fill = "palegreen2", color = "palegreen4", alpha = 0.7) +
  labs(title = "Trees - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

token_density <- ggplot(df_tokens, aes(x = log(RT))) +
  geom_density(fill = "darkgoldenrod1", color = "darkgoldenrod", alpha = 0.7) +
  labs(title = "Token - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

gaze_density <- ggplot(df_gaze, aes(x = log(RT))) +
  geom_density(fill = "lightpink", color = "lightpink4", alpha = 0.7) +
  labs(title = "Gaze - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

character_density <- ggplot(df_character, aes(x = log(RT))) +
  geom_density(fill = "aquamarine", color = "aquamarine4", alpha = 0.7) +
  labs(title = "Character - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

icon_density <- ggplot(df_icon, aes(x = log(RT))) +
  geom_density(fill = "plum", color = "plum4", alpha = 0.7) +
  labs(title = "Icon - Response Time: Density Plot", x = "RT", y = "Density") +
  theme_minimal()

# plot using patchwork
denity_response_times <- 
  (seed_density+tree_density)/
  (token_density+gaze_density)/
  (character_density+icon_density)

denity_response_times

rm(seed_density,
   tree_density,
   token_density,
   gaze_density,
   character_density,
   icon_density)
```

Modelling: Task with seed tokens

```{r}
# basic models
seed_m1 <- lmer(log(RT) ~ 1 + manipulation + age + gender + (1 |id), data = df_seed, subset = seed_response.corr == "1")
seed_m2 <- lmer(log(RT) ~ 1 + manipulation + age + gender + board_color + (1 |id), data = df_seed, subset = seed_response.corr == "1")

# controlling for stimulus order and which key was pressed
seed_m3 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_seeds.thisN + (1 |id), data = df_seed, subset = seed_response.corr == "1")
seed_m4 <- lmer(log(RT) ~ 1 + manipulation + age + gender + board_color + trials_seeds.thisN + (1 |id), data = df_seed, subset = seed_response.corr == "1")
seed_m5 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_seeds.thisN + correctSeednumber + (1 |id), data = df_seed, subset = seed_response.corr == "1")
seed_m6 <- lmer(log(RT) ~ 1 + manipulation + age + gender + board_color + trials_seeds.thisN + correctSeednumber + (1 |id), data = df_seed, subset = seed_response.corr == "1")

# controlling for having played the game
seed_m7 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_seeds.thisN + played_photo + (1 |id), data = df_seed, subset = seed_response.corr == "1")
seed_m8 <- lmer(log(RT) ~ 1 + manipulation + age + gender + board_color + trials_seeds.thisN + played_photo + (1 |id), data = df_seed, subset = seed_response.corr == "1")

# controlling for frequency of gaming
seed_m9 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_seeds.thisN + freq_game + (1 |id), data = df_seed, subset = seed_response.corr == "1")


```

Modelling: Task with tree colors

```{r}
# basic models
tree_m1 <- lmer(log(RT) ~ 1 + manipulation + age + gender + (1 | id), data = df_trees, subset = tree_response.corr == "1")
tree_m2 <- lmer(log(RT) ~ 1 + manipulation + age + gender + color_trees_to_count + (1 | id), data = df_trees, subset = tree_response.corr == "1")

# controlling for stimulus order and which key was pressed
tree_m3 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_tree.thisN + (1 | id), data = df_trees, subset = tree_response.corr == "1")
tree_m4 <- lmer(log(RT) ~ 1 + manipulation + age + gender + color_trees_to_count + trials_tree.thisN + (1 | id), data = df_trees, subset = tree_response.corr == "1")
tree_m5 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_tree.thisN + correctTreenumber + (1 | id), data = df_trees, subset = tree_response.corr == "1")
tree_m6 <- lmer(log(RT) ~ 1 + manipulation + age + gender + color_trees_to_count + trials_tree.thisN + correctTreenumber + (1 | id), data = df_trees, subset = tree_response.corr == "1")

# controlling for having played the game
tree_m7 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_tree.thisN + played_photo + (1 | id), data = df_trees, subset = tree_response.corr == "1")
tree_m8 <- lmer(log(RT) ~ 1 + manipulation + age + gender + color_trees_to_count + trials_tree.thisN + played_photo + (1 | id), data = df_trees, subset = tree_response.corr == "1")

# controlling for frequency of gaming
tree_m9 <- lmer(log(RT) ~ 1 + manipulation + age + gender + trials_tree.thisN + freq_game + (1 | id), data = df_trees, subset = tree_response.corr == "1")


```


```{r}
# make function for assessing AIC and BIC for various model fits

model_selection <- function(
  naming_scheme, 
  number_of_models) {

# generate model names
model_names <- paste0(naming_scheme, 1:number_of_models)

# create a list with the model names
model_list <- lapply(model_names, function(name) get(name))

# assign names to the elements in the list
names(model_list) <- model_names

# function to extract AIC and BIC values from fitted models
get_AIC_BIC <- function(model) {
  
  AIC_val <- AIC(model)
  BIC_val <- BIC(model)
  
  return(c(AIC_val, 
           BIC_val))
}

# apply the function to each model in the list
AIC_BIC_values <- sapply(model_list, get_AIC_BIC)

# creat table for easy overview
table <- data.frame(AIC = AIC_BIC_values[1, ], 
                    BIC = AIC_BIC_values[2, ])

return(table)

}

# apply the function to each of the tasks/investigations
seed_model_selection <- model_selection("seed_m", 9) 
tree_model_selection <- model_selection("tree_m", 9) 

```


Checking assumptions - residual plotting

```{r}
# list of selected models
models <- list(
  # seed_alm = lmer(log(RT) ~ 1 + manipulation + age + gender + trials_seeds.thisN + correctSeednumber + (1 |id), data = df_seed, subset = seed_response.corr == "1"),
  
  tree_m17 = lmer(log(RT) ~ 1 + manipulation + age + gender + trials_tree.thisN + correctTreenumber + (1 | id), data = df_trees, subset = tree_response.corr == "1"),
  
  tree_m17fam = glmer(RT ~ 1 + manipulation + age + gender + trials_tree.thisN + correctTreenumber + (1 | id), data = df_trees, subset = tree_response.corr == "1",
                  family = inverse.gaussian(link = "log"))#,

# seed_link = glmer(RT ~ 1 + manipulation + age + correctSeednumber + gender + trials_seeds.thisN + (1 | id), 
#                   data = df_seed, 
#                   subset = seed_response.corr == "1",
#                   family = inverse.gaussian(link = "log")),
# 
# seed_m17 = glmer(RT ~ 1 + manipulation + age + gender + trials_seeds.thisN + correctSeednumber + (1 | id), 
#                   data = df_seed, 
#                   subset = seed_response.corr == "1",
#                   family = Gamma(link = "log"))

  # seed_m1_trans = lmer(logRT ~ 1 + manipulation + age + trials_seeds.thisN + played_photo + (1 | id), data = df_seed, subset = seed_response.corr == "1"),
  # seed_m1_trans2 = lmer(logRT ~ 1 + manipulation + age + (1 | id), data = df_seed, subset = seed_response.corr == "1") 
)

# function to create residual plots 
create_residual_plot <- function(model, 
                                 model_name) {
  
  # extract residuals and fitted values
  residuals <- resid(model)
  fitted_values <- fitted(model)
  residual_data <- data.frame(Residuals = residuals, 
                              Fitted_Values = fitted_values)
  
  # plot 
  ggplot(residual_data, aes(x = Fitted_Values, y = Residuals)) +
    geom_point(color = "blue", 
               alpha = 0.7) +
    geom_hline(yintercept = 0, 
               linetype = "dashed", 
               color = "red") +
    labs(title = "Residuals vs Fitted Values", 
         subtitle = paste("Model:", model_name), 
         x = "Fitted Values", 
         y = "Residuals") +
    theme_minimal()
}

# make plots for each model
plots <- lapply(names(models), function(model_name) {
  create_residual_plot(models[[model_name]], model_name)
})

# arrange plots in grid
wrap_plots(plots)

```

QQ-plot

```{r}
# Q-Q plot of residuals
qqnorm(residuals(tree_m5))
qqline(residuals(tree_m5))
```

